from metafinder.utils.library import extract_metadata_from_google_search, extract_metadata_from_bing_search, extract_metadata_from_baidu_search
from metafinder.utils.library import extract_metadata_from_document
from metafinder.utils.exception import GoogleCaptcha, BaiduDetection, GoogleCookiePolicies